---
- name: Reload nginx
  ansible.builtin.command:
    cmd: "docker compose -f {{ application_compose_file_dest | default(compose_file_dest) }} exec -T nginx nginx -s reload"
  register: nginx_reload_result
  changed_when: true
  retries: 3
  delay: 2
  until: nginx_reload_result.rc == 0
