---
- name: Reload prometheus
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ prometheus_http_port }}/-/reload"
    method: POST
    status_code: [200]
  register: monitoring_prometheus_reload_result
  retries: 3
  delay: 2
  until: monitoring_prometheus_reload_result.status == 200
